-- | Synthesize the @Paths_<pkg>@ module that Cabal normally autogenerates
-- (spec §3). Many packages @import Paths_foo (version, getDataFileName)@, so
-- when zinc drives ghc directly it must provide this module itself. This is a
-- minimal, compile-clean stub sufficient for source builds where data files
-- resolve relatively.
--
-- Beyond Cabal's surface, zinc also exposes consistent GIT VERSION METADATA on
-- every built package (zinc-3x4): @gitHash@, @gitCommitCount@, @gitDirty@ and a
-- combined @fullVersion@, derived from a workspace member's working tree or a
-- dependency's pinned commit. These are extra top-level bindings (a 'Version'
-- cannot carry a tag) for zinc-aware code / git-derived versioning to consume.
module Zinc.Paths
  ( pathsModuleName
  , synthesizePaths
  ) where

import Zinc.Git (GitMeta (..))
import Zinc.Version (gitVersion)

-- | The autogenerated module name for a package: @Paths_<name>@ with dashes
-- replaced by underscores (e.g. @my-pkg@ → @Paths_my_pkg@).
pathsModuleName :: String -> String
pathsModuleName pkg = "Paths_" ++ map dashToUnderscore pkg
  where
    dashToUnderscore '-' = '_'
    dashToUnderscore c   = c

-- | Render the @Paths_<pkg>@ module source for a package: its version, the Cabal
-- data-file stubs, and zinc's git version metadata ('GitMeta', zinc-3x4).
synthesizePaths :: String -> [Int] -> GitMeta -> String
synthesizePaths pkg version meta =
  unlines
    -- Neutralize package-wide default-extensions that would break this vanilla
    -- stub. A package can declare e.g. NoImplicitPrelude + RebindableSyntax
    -- (basement, foundation), which then apply to the synthesized Paths module
    -- too — desugaring its literals / `return` / lists through out-of-scope
    -- rebound names (GHC-76037). A module-level LANGUAGE pragma overrides
    -- default-extensions, so force the Prelude back on and rebindable syntax off
    -- here; the stub then compiles regardless of the package's defaults (zinc-2lv).
    [ "{-# LANGUAGE NoRebindableSyntax #-}"
    , "{-# LANGUAGE ImplicitPrelude #-}"
    , "module " ++ moduleName
        ++ " (version, gitHash, gitCommitCount, gitDirty, fullVersion, getDataFileName, getDataDir, getBinDir, getLibDir, getSysconfDir) where"
    , ""
    , "import Data.Version (Version, makeVersion)"
    , ""
    , "version :: Version"
    , "version = makeVersion " ++ show version
    , ""
    , "-- zinc git version metadata (zinc-3x4)"
    , "gitHash :: String"
    , "gitHash = " ++ show (gmHash meta)
    , ""
    , "gitCommitCount :: Int"
    , "gitCommitCount = " ++ show (gmCommitCount meta)
    , ""
    , "gitDirty :: Bool"
    , "gitDirty = " ++ show (gmDirty meta)
    , ""
    , "-- the package version plus a git tag (short hash, +dirty) when available"
    , "fullVersion :: String"
    , "fullVersion = " ++ show fullVersion
    , ""
    , "getDataFileName :: FilePath -> IO FilePath"
    , "getDataFileName name = return name"
    , ""
    , "getDataDir, getBinDir, getLibDir, getSysconfDir :: IO FilePath"
    , "getDataDir = return \".\""
    , "getBinDir = return \".\""
    , "getLibDir = return \".\""
    , "getSysconfDir = return \".\""
    ]
  where
    moduleName = pathsModuleName pkg
    base = intercalateDots version
    -- Same format as `zinc version` (Zinc.Version.gitVersion), so an app's
    -- Paths_<pkg>.fullVersion matches zinc's own convention (zinc-b3z/ij5).
    fullVersion = gitVersion base (gmHash meta) (gmCommitCount meta) (gmDirty meta)
    intercalateDots [] = "0"
    intercalateDots xs = drop 1 (concatMap (('.' :) . show) xs)
