-- | Synthesize the @Paths_<pkg>@ module that Cabal normally autogenerates
-- (spec §3). Many packages @import Paths_foo (version, getDataFileName)@, so
-- when zinc drives ghc directly it must provide this module itself. This is a
-- minimal, compile-clean stub sufficient for source builds where data files
-- resolve relatively.
module Zinc.Paths
  ( pathsModuleName
  , synthesizePaths
  ) where

-- | The autogenerated module name for a package: @Paths_<name>@ with dashes
-- replaced by underscores (e.g. @my-pkg@ → @Paths_my_pkg@).
pathsModuleName :: String -> String
pathsModuleName pkg = "Paths_" ++ map dashToUnderscore pkg
  where
    dashToUnderscore '-' = '_'
    dashToUnderscore c   = c

-- | Render the @Paths_<pkg>@ module source for a package and its version.
synthesizePaths :: String -> [Int] -> String
synthesizePaths pkg version =
  unlines
    [ "module " ++ moduleName
        ++ " (version, getDataFileName, getDataDir, getBinDir, getLibDir, getSysconfDir) where"
    , ""
    , "import Data.Version (Version, makeVersion)"
    , ""
    , "version :: Version"
    , "version = makeVersion " ++ show version
    , ""
    , "getDataFileName :: FilePath -> IO FilePath"
    , "getDataFileName name = return name"
    , ""
    , "getDataDir, getBinDir, getLibDir, getSysconfDir :: IO FilePath"
    , "getDataDir = return \".\""
    , "getBinDir = return \".\""
    , "getLibDir = return \".\""
    , "getSysconfDir = return \".\""
    ]
  where
    moduleName = pathsModuleName pkg
